# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaatic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='n_comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='blog',
            new_name='library',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='n_pingbacks',
            new_name='pingbacks',
        ),
        migrations.RenameField(
            model_name='leaf',
            old_name='pub_date',
            new_name='posted_date',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='leaf',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='leaf',
            name='n_comments',
        ),
        migrations.RemoveField(
            model_name='leaf',
            name='n_pingbacks',
        ),
        migrations.RemoveField(
            model_name='leaf',
            name='rating',
        ),
        migrations.AddField(
            model_name='leaf',
            name='chapter',
            field=models.ForeignKey(default=1223, on_delete=django.db.models.deletion.CASCADE, to='bookmaatic.Chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaf',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmaatic.Book'),
        ),
    ]
