# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaatic', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='comments',
            new_name='comment_feature',
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookmaatic.Book'),
        ),
    ]
