# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaatic', '0006_auto_20170324_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='comment_feature',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
