# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 17:04
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmaatic', '0007_auto_20170324_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=2, storage=django.core.files.storage.FileSystemStorage(location='/media/images'), upload_to=''),
            preserve_default=False,
        ),
    ]
